-- ==========================================
-- SUPER FAST FIXES & FACE API ADVANCEMENT V8
-- ==========================================

-- 1. Fix RLS for the Orders table so Anonymous users (customers) can place orders.
DROP POLICY IF EXISTS "Public Order Insert" ON orders;
CREATE POLICY "Public Order Insert" ON orders
    FOR INSERT 
    WITH CHECK (true);

-- Also allow customers to select their own orders if they just placed them (optional but good practice)
DROP POLICY IF EXISTS "Public Order Select" ON orders;
CREATE POLICY "Public Order Select" ON orders
    FOR SELECT 
    USING (true);

-- 2. Add Face Descriptor column for Face Recognition Attendance
-- We use JSONB to neatly store the 128-dimensional float array generated by face-api.js
ALTER TABLE staff
ADD COLUMN IF NOT EXISTS face_descriptor jsonb;

-- Just in case the owner is stored differently, apply to staff_profiles as well
ALTER TABLE staff_profiles
ADD COLUMN IF NOT EXISTS face_descriptor jsonb;
